apiVersion: apps/v1 
kind: Deployment
metadata:
  name: app2  
  ########### Replica set labels ###############
  labels: 
    purpose: ingress-demo
    project: roboshop
    app: app2
spec:
  replicas: 2
  selector:
  ######### These are used to select pods ##############
    matchLabels:
      ## purpose: dp-demo
      purpose: ingress-demo
      project: roboshop
      app: app2
### pod definition ########

  template:
    metadata:
      labels:
        purpose: ingress-demo
        project: roboshop
        app: app2
    spec:
      containers:
        - name: app2
          image: naresh1567/app2:v1

---
apiVersion: v1 
kind: Service
metadata:
    name: app2
spec:    
    selector:
      purpose: ingress-demo
      project: roboshop
      app: app2
    ports:
    - protocol: TCP
      port: 80 ## service port
      targetPort: 80 ## container port

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app2
  annotations: 
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:196061557907:certificate/191f2f60-c34c-4198-a1cc-fc498827184b
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/tags: Environment=dev,Project=roboshop
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/group.name: roboshop ## this is used to group multiple ingresses into a single ALB
    
spec:
  ingressClassName: alb
  rules:
  - host: "app2.daws86s.store"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: app2
            port:
              number: 80
  

